### ISSUE TITLE
next build がコケる

### ISSUE THREAD

**Issue by Azuki-bar** [ueckoken/chofu-race-course#70]
```
 !  ~/g/chofu-race-course   feat/js-container …  client  yarn next build
info  - Linting and checking validity of types
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
[    ] info  - Generating static pages (0/8)TypeError: Cannot read properties of undefined (reading 'data')
    at RaceDetailPage (/home/azukibar/github/chofu-race-course/client/.next/server/pages/race/0.js:36:40)
    at Wc (/home/azukibar/github/chofu-race-course/client/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/home/azukibar/github/chofu-race-course/client/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/home/azukibar/github/chofu-race-course/client/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/home/azukibar/github/chofu-race-course/client/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/home/azukibar/github/chofu-race-course/client/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
    at Z (/home/azukibar/github/chofu-race-course/client/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/home/azukibar/github/chofu-race-course/client/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/home/azukibar/github/chofu-race-course/client/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/home/azukibar/github/chofu-race-course/client/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)

Error occurred prerendering page "/race/0". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'data')
    at RaceDetailPage (/home/azukibar/github/chofu-race-course/client/.next/server/pages/race/0.js:36:40)
    at Wc (/home/azukibar/github/chofu-race-course/client/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/home/azukibar/github/chofu-race-course/client/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/home/azukibar/github/chofu-race-course/client/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/home/azukibar/github/chofu-race-course/client/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/home/azukibar/github/chofu-race-course/client/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
    at Z (/home/azukibar/github/chofu-race-course/client/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/home/azukibar/github/chofu-race-course/client/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/home/azukibar/github/chofu-race-course/client/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/home/azukibar/github/chofu-race-course/client/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
info  - Generating static pages (8/8)

> Build error occurred
Error: Export encountered errors on following paths:
	/race/0
    at /home/azukibar/github/chofu-race-course/client/node_modules/next/dist/export/index.js:404:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (/home/azukibar/github/chofu-race-course/client/node_modules/next/dist/trace/trace.js:79:20)
    at async /home/azukibar/github/chofu-race-course/client/node_modules/next/dist/build/index.js:1229:21
    at async Span.traceAsyncFn (/home/azukibar/github/chofu-race-course/client/node_modules/next/dist/trace/trace.js:79:20)
    at async /home/azukibar/github/chofu-race-course/client/node_modules/next/dist/build/index.js:1091:17
    at async Span.traceAsyncFn (/home/azukibar/github/chofu-race-course/client/node_modules/next/dist/trace/trace.js:79:20)
    at async Object.build [as default] (/home/azukibar/github/chofu-race-course/client/node_modules/next/dist/build/index.js:65:29)
```

**Comment by Azuki-bar** [comment]
どうも https://github.com/ueckoken/chofu-race-course/blob/ca524016315acc28a98253a419416fd1382f15b6/client/src/pages/race/0.tsx#L15 の`dataTimeToHHMM`を消して `!.`を`?.`にしたらコンパイルが通った
なんで

**Comment by Azuki-bar** [comment]
```diff
diff --git a/client/src/pages/race/0.tsx b/client/src/pages/race/0.tsx
index 3664d8b..32c3d23 100644
--- a/client/src/pages/race/0.tsx
+++ b/client/src/pages/race/0.tsx
@@ -1,7 +1,6 @@
 import { FC } from "react";
 import Link from "next/link";
 import { RaceDataResponse } from "../../../_proto/spec/v1/userdata_pb";
-import { dateToHHmm } from "../../util/time";
 import { raceOrderToString } from "../../util/util";
 
 const res = new RaceDataResponse();
@@ -10,9 +9,8 @@ const raceData = res.race;
 const RaceDetailPage: FC<{}> = () => {
     return (
         <>
-            <h2>{`第${raceData!.data!.order}競争 ${raceData!.data!.name}`}</h2>
-            <p>{raceData!.description}</p>
-            <p>{`${dateToHHmm(raceData!.data!.start!.toDate())}発走`}</p>
+            <h2>{`第${raceData?.data?.order}競争 ${raceData?.data?.name}`}</h2>
+            <p>{raceData?.description}</p>
             <h3>出走馬</h3>
             <table>
                 <tr>
@@ -22,12 +20,12 @@ const RaceDetailPage: FC<{}> = () => {
                     <th>オッズ</th>
                     <th>人気</th>
                 </tr>
-                {raceData!.members.map((e) => (
-                    <tr key={`horse${e.horse!.id}`}>
+                {raceData?.members.map((e) => (
+                    <tr key={`horse${e.horse?.id}`}>
                         <td>{raceOrderToString(e.order!)}</td>
                         <td>
-                            <Link href={`/horse/${e.horse!.id}`}>
-                                <a>{e.horse!.name}</a>
+                            <Link href={`/horse/${e.horse?.id}`}>
+                                <a>{e.horse?.name}</a>
                             </Link>
                         </td>
                         <td>
```
こうしたらコンパイルできるようになった
なんで？
